<template>
  <main style="background-color: #556cff">
    <div class="container py-5">
      <div class="row mb-4">
        <h4 style="color: white; font-weight: bold">
          기관(마포중앙도서관) 실내데이터
        </h4>
      </div>
      <div class="container">
        <div class="row mt-5">
          <div class="col-md-4 mb-3 rounded-4"
            style="text-align: center;">
            <div class="container">
              <p style="color: white; font-weight: bold"></p>
              <div :key="floor" v-for="floor in floorDataList" class="row mb-2 rounded-3"
                style="background-color: white; cursor: pointer">
                <text class="my-2" @click="changeFloor(floor.floorNumber)">
                  {{ floor.value }}
                </text>
              </div>
            </div>
          </div>
          <div class="col-md-8 mb-3 align-self-center">
            <div class="row-md-8 px-4 py-4 rounded-4" style="background-color: #e6ebf5;">
              <!-- Image Map Generated by http://www.image-map.net/ -->
              <img
                :src="imgSrc"
                usemap="#image-map"
                id="img_ID"
                @load="imgResize()"
                class="img-fluid"
              />
              <map name="image-map" id="map_ID">
                <area
                  :key="map.alt"
                  v-for="map in mapSrc"
                  :shape="map.shape"
                  :coords="map.coords"
                  :title="map.title"
                  @mouseover="over(map.target)"
                  @mouseout="out"
                />
              </map>
            </div>
          </div>
          <div class="row-md-4 mb-2">
            <div class="row-md-2 mb-1 py-2 rounded-4" style="background-color: #ffffff; text-align: center;">
              <div :key="i" v-for="(filter, i) in filterInfo">
                <input
                  type="checkbox"
                  name=""
                  :id="filter.id"
                  :value="filter.value"
                  v-model="checkedFilter"/>
                <label :for="filter.id">{{ filter.name }}</label>
              </div>
            </div>
          </div>
        </div>
      </div>
      <text style="color: white">
        {{ sampleData }}
      </text>
    </div>
  </main>
</template>

<script>
import imgMap from '../assets/imgMap/map'
export default {
  setup () {},
  data () {
    return {
      title: '',
      floor: 0, // 현재 보여줄 층 번호
      floorDataList: [],
      filterInfo: [
        {
          name: '온도 데이터',
          id: 'temp',
          value: 'Temp'
        },
        {
          name: '습도 데이터',
          id: 'hum',
          value: 'Hum'
        },
        {
          name: '미세먼지 데이터',
          id: 'pm',
          value: 'Pm'
        },
        {
          name: '소음 데이터',
          id: 'db',
          value: 'Db'
        }
      ],
      checkedFilter: [],
      sampleData: 'Out',
      imgSrc: '',
      mapSrc: [],
      width: 0
    }
  },
  methods: {
    changeFloor (currentFloor) {
      this.$router.push({
        path: '/inner',
        query: { floor: currentFloor }
      })
      this.floor = currentFloor
      this.setSrc()
    },
    setSrc () {
      this.mapSrc = imgMap[this.floor]
      this.imgSrc = require('../assets/imgMap/img_facility_floor_' +
        this.floor + 'F.png')

      const img = new Image()
      img.src = this.imgSrc
      this.width = img.width
    },
    over (title) {
      this.sampleData = title + ' 접근'
      this.sampleData += ' ' + this.checkedFilter
    },
    out () {
      this.sampleData = 'Out'
    },
    /* eslint-disable one-var */
    imgResize () {
      let previousWidth = this.width
      const ImageMap = function (map, img) {
          const areas = map.getElementsByTagName('area'),
            len = areas.length,
            coords = []

          for (let n = 0; n < len; n++) {
            coords[n] = areas[n].coords.split(',')
          }
          this.resize = function () {
            const x = img.offsetWidth / previousWidth
            for (let n = 0; n < len; n++) {
              const clen = coords[n].length
              for (let m = 0; m < clen; m++) {
                coords[n][m] *= x
              }
              areas[n].coords = coords[n].join(',')
            }
            previousWidth = img.offsetWidth
            return true
          }
          window.onresize = this.resize
        },
        imageMap = new ImageMap(
          document.getElementById('map_ID'),
          document.getElementById('img_ID')
        )
      imageMap.resize()
    }
  },
  created () {
    this.floor = this.$route.query.floor
    this.floorDataList = this.$store.state.floorDataList
    this.setSrc()
  }
}
</script>
